[program:queue-worker]
command=php /var/www/html/artisan queue:work redis
    --sleep=3
    --tries=3
    --max-time=3600
    --no-interaction

process_name=%(program_name)s_%(process_num)02d
; Increase numprocs to run more parallel queue workers
numprocs=2

autostart=true
autorestart=true
startsecs=5
startretries=3
stopwaitsecs=3600

user=laravel
redirect_stderr=true
stdout_logfile=/var/log/supervisor/queue-worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
